Open-Web-Analytics/Open-Web-Analytics

- wp_plugin.php
Bumped the version displayed to 1.6.0 to match the code.
> Version bump to 1.6.0

- owa_lib.php
Try HTTP_ORIGIN before HTTP_REFERER since HTTP_ORIGIN
is supposed to be the more reliable var.
> Fix for issue #101

- modules/base/entities/user.php
This fixes a bug during setup.
> Removed duplicate table attribute AUTO_INCREMENT

- owa_lib.php
Warning: Use of undefined constant password_hash - assumed 'password_hash' (this will throw an Error in a future version of PHP) in /www/htdocs/w014f66b/dev.winhelp.shop/owa/owa_lib.php on line 1009
> Bugfix: Use of undefined constant password_hash

- LICENCE
Based on information's from http://www.openwebanalytics.com/
> Add: Licence file

- modules/base/handlers/notifyHandlers.php
> Bugfix: No mail for new visitors where send

- modules/base/classes/installController.php
- modules/base/classes/installManager.php
- modules/base/entities/user.php
- modules/base/installBase.php
- modules/base/installCli.php
- modules/base/installEmbedded.php
- modules/base/templates/install_defaults_entry.php
- modules/base/templates/users_addoredit.tpl
- modules/base/usersEdit.php
> Feature: Added possibility to set custom admin name

- modules/base/reportGoalFunnel.php
- modules/base/templates/header.tpl
- modules/base/templates/report_goal_funnel.php
- modules/base/templates/sites.tpl
> Bugfix: User see site links even if they have no permission

- modules/base/changeUserPasswordCli.php
- modules/base/classes/userManager.php
- modules/base/module.php
- modules/base/usersChangePassword.php
- modules/base/usersSetPassword.php
/path/to/php5 cli.php cmd=change-password
Arguments
''user'' '''required''' - user_id of the user
''password'' ''required'' - new password
Ref: #47
> Feature: Password change via cli command

- owa_auth.php
See: https://stackoverflow.com/a/51128675
Ref: #449
> Bugfix: Support for "SameSite" origin changes

- modules/base/classes/settings.php
- modules/base/widgetOwaNews.php
> Bugfix: Updated repository api url and request logic

- modules/base/js/owa.tracker-combined-min.js
- modules/base/js/owa.tracker.js
> Bugfix: Vertical Scrollbar flickering during tracking

- modules/base/classes/settings.php
- modules/base/installConfig.php
- modules/base/templates/install_config_entry.php
- modules/base/templates/install_start_embedded.tpl
- owa-config-dist.php
- owa_base.php
- owa_coreAPI.php
- owa_db.php
- plugins/db/owa_db_mysql.php
> Feature: MySQL port option

- .github/ISSUE_TEMPLATE/01_Bug.md
- .github/ISSUE_TEMPLATE/02_Feature.md
- .github/ISSUE_TEMPLATE/03_Support.md
- .github/PULL_REQUEST_TEMPLATE.md
Added these files to make issues and pr´s more clearly
> Git special files

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> Git special files refactor

- modules/base/crawlDocumentCli.php
- modules/base/entities/document.php
- modules/base/module.php
- owa_httpRequest.php
```bash
/path/to/php cli.php cmd=update-document
```
* ''doc'' ''(optional)''' - owa_document::id
> Feature: CLI Command to re-crawl Document URLs

- .github/ISSUE_TEMPLATE/04_Installation.md
Added this template for installations. Hopefully the users will create issues with this template instead of creating blank ones.
> Added issue template for installations

- modules/base/classes/error.php
- modules/base/classes/mailer.php
- modules/base/classes/userManager.php
- modules/base/controllers/addSiteRestController.php
- modules/base/controllers/addUserRestController.php
- modules/base/controllers/deleteUserRestController.php
- modules/base/controllers/siteAddAllowedUserRestController.php
- modules/base/controllers/sitesRestController.php
- modules/base/controllers/usersRestController.php
- modules/base/entities/user.php
- modules/base/module.php
- modules/base/sites.php
- modules/base/sitesEditAllowedUsers.php
- modules/base/templates/restApiResponse.php
- modules/base/templates/sites_addoredit.tpl
- modules/base/users.php
- modules/base/usersAdd.php
- modules/base/usersDelete.php
- modules/base/usersNewAccount.php
- owa_controller.php
- owa_coreAPI.php
- owa_entity.php
- owa_requestContainer.php
- plugins/validations/inArray.php
- plugins/validations/isNotCurrentUser.php
- added multiple new REST rotes for GET/POST/DELETE operations on Users, Sites, and SiteUsers
- refactored old controllers to allow for inheretance by new REST controllers
- refactored http request param setting for DELETE and PUT requests
- refactored controller execution flow to fix bug where event handlers were not able to trigger their own follow-on controllers
- fixed bug in error reporting level
- added inArraya nd isNotCurrentUser validations
- added vlidations to Uer controllers
- Properly set http response codes on all REST API requests.
I renamed the `siteProfile` routes that I recently added to solidify a good naming convention. Won't have to do this again. The few …
> More REST API Routes and Changes

- modules/base/classes/column.php
- modules/base/classes/resultSetManager.php
- wp_plugin.php
- Issue Numbers: #577 #578 
-  Also stopped WP Plugin from displaying admin notices multiple times.
> Bugfix: fixing random notices and admin_notices in WP Plugin.

- modules/base/installBase.php
- modules/base/js/owa.heatmap.js
- modules/base/module.php
- modules/base/usersAdd.php
I tested but please test heat maps on a site with lots of clicks to see if it's doing multiple API calls for data.
Issue Number: #591 
Also, heat map was not fetching all clicks. It should do this by making multiple queries to the backend. This wasn't happening due to a flat being set to false in it's default config. also i bumped the z-index of the overlay because on some websites it wasn't high enough.
> Random Login and heat map Bugs

- cli.php
This commit uses php_sapi_name() against a definite value, rather than
relying on the absense of various superglobals to determine CLI context.
If HTTP is detected, a 404 is issued.
It also adds some additional CLI error outputs, and exit codes for basic
invocation.
- calls to cli.php from HTTP result in 200 response with blank page
- CLI context determined by heuristics
- No CLI errors written
- No error handling for invalid argument syntax
- Success exit code on CLI invocation errors
- calls to cli.php from HTTP result in 404 response with blank page. This is considered an improvement as it suggests there's nothing here, which might fool detection bots (e.g. …
> Improve calling context checks on cli.php

- conf/searchengines.php
- conf/socialnetworks.php
- modules/base/classes/trackingEventHelpers.php
- modules/base/module.php
- modules/base/src/tracker/Tracker.js
- owa_coreAPI.php
- owa_env.php
- owa_requestContainer.php
- [x ] Tested the changes
- [x ] Build (`/path/to/php cli.php cmd=build`) was run locally and any changes were pushed
Currently inferences about the medium and source of traffic are inferred by the tracker clients. this requires that we update the list of search engines and social networks in the trackers themselves. 
This PR moves the same inference logic to the server side and removes it from the javascript tracker. 
This doesn't break anything but it deprecates the use of the tracker's `addOrginicSearchEngine` method. Instead additional search engines and social neotwkrs can be added two ways:
- via new filters `tracking.organic_search_engine_registry` and …
> Move traffic attribution inference to server side

- modules/base/classes/error.php
- modules/base/classes/state.php
- modules/base/module.php
- modules/base/report.php
- owa_auth.php
- owa_coreAPI.php
- owa_metric.php
- owa_module.php
- owa_template.php
- owa_view.php
PHP8 related errors due to changes in PHP (attributes must be declared before being set, optional parameters cannot come before required parameters, and extended class method declarations must be compatible with the parent class)
PHP8.0|1.x produces errors related to changes in the syntax strictness of PHP.
Issue Number: 893
Less errors are produced for PHP8.0|1.x environments.
-
-
-
> Criterion9 php8 dynamic attributes and other similar php version change issues

- composer.lock
- modules/base/classes/settings.php
- modules/base/handlers/documentHandlers.php
- owa-config-dist.php
- owa_entity.php
**### Feature**
Added the updating of the page title and type to an existing document when the tracer request is processed. This is activated by a new config constant.
> Feature - allow document updating
