Open-Web-Analytics/Open-Web-Analytics

- owa_template.php
Visiting OWA on HTTPS will cause browser partially insecure content warning, due to fetching of Gravatar and WP thumbnail over HTTP.
> Added HTTPS support for WP sites

- modules/base/js/owa.tracker.js
Move the clearInterval above the iframe data push to prevent race conditions where duplicate data gets logged/tracked.
> Update owa.tracker.js to prevent race condition with duplicate tracked events

- modules/base/js/owa.areachart.js
Listing the same property twice in one object literal is redundant and may indicate a copy-paste mistake.
In ECMAScript 2015 and above, as well as ECMAScript 5 non-strict mode, an object literal may define the same property multiple times, with later definitions overwriting earlier ones. If all definitions assign the same value to the property, this will not to lead to problems at runtime, but it makes the code harder to read and maintain.
> Duplicate property

- modules/base/templates/config_dom.tpl
Fix for PHP warning: 
PHP Warning:  Use of undefined constant OWA_ERROR_HANDLER - 
assumed 'OWA_ERROR_HANDLER' (this will throw an Error in a future version of PHP) in /public_html/owa/modules/base/templates/config_dom.tpl on line 15
> Fix: Use of undefined constant OWA_ERROR_HANDLER

- owa_auth.php
- owa_lib.php
new functions added for encrypting passwords with better algorithm, while keeping support for older passwords and older versions of php, that do not containing the recommended password functions
https://github.com/padams/Open-Web-Analytics/issues/386
> new functions added for encrypting passwords

- owa_lib.php
Hi,
i am getting error while install of ``Open Web Analytics`` 1.6.4
```
Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in plugins/db/owa_db_mysql.php on line 220
Fatal error: Using $this when not in object context in owa_lib.php on line 1012
```
after debug i found
```php
/**
* Simple Password Encryption
*
* @param string $password
* @return string
*/
public static function encryptOldPassword($password) {
return md5(strtolower($password).strlen($password));
//return owa_coreAPI::saltedHash( $password, 'auth');
}
public static function encryptPassword($password) {
// check function exists to support older PHP
if ( function_exists(password_hash) ) {
return password_hash( $password, PASSWORD_DEFAULT );
} else {
return …
```
> Getting Error while install of Open Web Analytics 1.6.4

- modules/base/reportAttributionHistory.php
Uncaught SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse (<anonymous>)
at HTMLTableElement.dim.options.grid.columnFormatters.latestAttributions (index.php?owa_siteId=XXX&owa_period=last_seven_days&owa_do=base.reportAttributionHistory:425)
at M (owa.reporting-combined-min.js?version=1.6.4:2310)
at R (owa.reporting-combined-min.js?version=1.6.4:2310)
at ra (owa.reporting-combined-min.js?version=1.6.4:2320)
at HTMLTableElement.a.addJSONData (owa.reporting-combined-min.js?version=1.6.4:2374)
at OWA.dataGrid.addAllRowsToGrid (owa.reporting-combined-min.js?version=1.6.4:2904)
at OWA.dataGrid.display (owa.reporting-combined-min.js?version=1.6.4:2904)
at OWA.dataGrid.generate (owa.reporting-combined-min.js?version=1.6.4:2904)
at OWA.resultSetExplorer.createGrid …
> Bugfix: Fixed a bug where already parsed json is parsed a second time

- modules/base/classes/settings.php
- owa_coreAPI.php
Added option to disable cookie persistence. This feature will disable the "unique visitor" functionality, because the cookies are session cookies only.
This is useful in europe, where you have to add a cookie consent tool when you have persistent tracking cookies on our site.
My experience is that nowadays many visitors won´t accept such cookies and you can not track them. This is also why I switched from Google Analytics to OpenWebAnalytics.
> Feature: Global settings for cookie persistence

- modules/base/classes/trackingEventHelpers.php
Manually set location properties like the following getting ignored.
```
$owa = new owa_php();
$owa->setProperty('country', 'Germany');
```
Because `owa_trackingEventHelpers::resolveCountry` returns null, when the value is already set.
So `owa_eventDispatch::filter` assigns null to the value variable and returns null.
Which result in `owa_trackingEventHelpers::setTrackerProperties` overriding the already set property with null, in line 138.
> Bugfix: Manually provided location properties getting ignored

- plugins/db/owa_db_mysql.php
mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, bool given in /var/www/owa/plugins/db/owa_db_mysql.php on line 220
Ref: #432
> Bugfix: Catch query errors

- modules/base/templates/report_visitor.tpl
- owa_template.php
Always respond with 404, because url always gets '(not set)' prepended.
#456 #396
> Bugfix: Visitor history avatar not displayed when visitor_avatar_id not set

- conf/messages.php
- modules/base/classes/installController.php
- modules/base/classes/installManager.php
- modules/base/classes/sanitize.php
- modules/base/installCheckEnv.php
- modules/base/passwordResetRequest.php
- modules/base/templates/apiError.php
- modules/base/templates/error_validation_summary.tpl
- modules/base/templates/msgs.tpl
- modules/base/updates/004.php
- owa_base.php
- owa_view.php
> Bugfix: Template content being 'escaped' showing HTML entities

- owa_httpRequest.php
I changed the regex for title extraction because facebook title couldn´t extracted.
I could reproduce #518 at all
> Bug: Referral html content shown in Referra

- modules/base/templates/sites_addoredit.tpl
Issue Number: #538 
The link points now to https://www.w3.org/P3P/
> Bugfix: Wrong link for P3P Compact Privacy Policy in site settings

- modules/base/templates/report_visit.tpl
Issue Number: #545 
If there are less than two digits in hour, minute or second leading zeros gets displayed now
> Bugfix: time stamps in clickstream zeros get not displayed

- modules/base/templates/users_change_password.tpl
- modules/base/usersChangePassword.php
- modules/base/usersPasswordEntry.php
- modules/base/usersSetPassword.php
- owa_caller.php
- wp_plugin.php
Issue Number: #446 
Refactoring the WordPress plugin in preparation for separation into its own repository.
- Completely new plugin settings screens that control the configuration of the OWA tracker snippet
- Use of the REST API to select the siteId to track
- removal of OWA as a library dependency when including the tracking tag in pages
- Removal of link to OWA instance configuration
- added proper admin menu icon
- added features to allow tracking of wp-admin pages
> WordPress Plugin Changes

- owa_coreAPI.php
Looks like a clear bug to me. Unless there's something about variable scope I (and my IDE) have to learn.
No issue filed. Trivial bug referencing undefined variable in an error reporting string.
- Not relevant ... clearly untested code (as it would I am guessing bomb with an unreferenced variable error if ever hit)
> connection_class_path is not defined in this context

- log.php
Fix missing C on printf
A fresh install throw an error with printf on line 72 of log.php and the server return with a 500.
Issue Number: #755 
With the correct printf format, the server return 200 and analytics works ok
> Fix problem with printf on log.php that throw error.

- owa_entity.php
executeQuery returns a truthy value if successful. In the postgresql case it is a string like "resource id='79' type='pgsql result'". I'm a bit puzzled why bools are tested against "=== true"  at all, and being a bool they can be tested just fine in an if, while the if also works for truthy and falsey values.
-
-
-
> Fixing caching bug

- modules/base/js/owa.tracker.js
Got Uncaught TypeError: window[obj_name][method] is undefined when I pushed owa_cmds.push(['unpause-owa']); while owa was not paused, because it would try to use the method on OWATracker. This should fix this Issue.
- [ X] Bugfix
Currently pushing owa_unpause also got send to OWATracker and caused an error.
- owa_pause is no longer send to OWATracker
-
-
- [ X] No
- [X ] No
> Fixed Error where pushing ['unpause-owa'] leads to TypeError

- modules/base/classes/resultSetManager.php
- modules/base/classes/trackingEventHelpers.php
- owa_requestContainer.php
- plugins/db/owa_db_mysql.php
- [N/A] Build (`/path/to/php cli.php cmd=build`) was run locally and any changes were pushed
Checks for null values before passing variables through to base php functions.
Logs get filled with repeating deprecation warnings when filter/validating strings that are null. When trying to debug the deprecation warnings from passing null values to base php functions was making it difficult to scan the logs. This patch just targeted the frequent offenders by returning early if the value was null instead of a string.
Null variables are not further validated or filtered and the methods return early.
-
-
-
> String null filter patch

- owa_db.php
- plugins/db/owa_db_mysql.php
This PR includes 2 adjustments to db handling based on changes in how PHP handles/returns things. 
PHP 8.x sometimes throws errors from empty query results or any variety of exceptions that could be thrown when using the mysqli query functions.
Issue Number: 893
Less errors produced when using php 8.x (tested with 8.1 & 8.2)
-
-
-
> Criterion9 php 8 db handling
